- name: Create user and copy passwd file
  hosts: all
  tasks:
    - name: User creation
      user:
        name: aziz
        password: aziz
        uid: 6779
        home: /home/aziz
    - name: Copy password into users home dir
      copy:
        src: /etc/passwd
        dest: /home/aziz
---
# with variables
- name: Create user and copy passwd file
  hosts: all
  vars:
    - username: aziz
  tasks:
    - name: User creation
      user:
        name: "{{username}}"
        password: "{{username}}"
        uid: 6779
        home: /home/{{username}}
    - name: Copy password into users home dir
      copy:
        src: /etc/passwd
        dest: /home/{{username}}
