#reading register to pass output of command as variable

---
- name: create ssh key for the gitlab account 
  hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: Generate /etc/ssh/ RSA host key
    command : ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
    args:
      creates: /etc/ssh/ssh_host_rsa_key
  - name: "Read a file content"
    shell: |
      cat /etc/ssh/ssh_host_rsa_key.pub
#pass output of cat as variables using register
    register: file_content
  - name: "Print the file content to a console"
#output the variable 
    debug:
      msg: "{{ file_content.stdout }}"
  - name: "Save the file content to a '$host_conf' variable"
    set_fact:
      host_conf: "{{ file_content.stdout }}"
  - name: "Print the '$host_conf' variable"
    debug:
      msg: "{{ host_conf }}"